name: TraMSD
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11.4
  - pip
  - libgcc-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.10
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - libffi=3.4.4
  - ld_impl_linux-64=2.38
  - libgomp=11.2.0
  - libstdcxx-ng=13.2.0
  - libuuid=1.41.5
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - xz=5.4.2
  - zlib=1.2.13
  - cudatoolkit=11.8
  - cudnn=8.9.2
  - torchaudio
  - pytorch-cuda=11.8
  - torchvision==0.15.2
  - pip:
      - anyio==4.0.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cmake==3.27.4.1
      - comm==0.1.4
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - executing==2.0.0
      - fastjsonschema==2.18.1
      - filelock==3.12.3
      - fqdn==1.5.1
      - fsspec==2023.9.0
      - gitdb==4.0.10
      - gitpython==3.1.37
      - huggingface-hub==0.16.4
      - idna==3.4
      - ipykernel==6.26.0
      - ipython==8.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.5.0
      - jupyter-console==6.6.3
      - jupyter-core==5.4.0
      - jupyter-events==0.8.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.9.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.7
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - lit==16.0.6
      - markupsafe==2.1.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numpy==1.25.1
      - opencv-python==4.8.0.76
      - overrides==7.4.0
      - packaging==23.1
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - platformdirs==3.11.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pygments==2.16.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.1
      - regex==2023.8.8
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.6
      - safetensors==0.3.3
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - send2trash==1.8.2
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - tornado==6.3.3
      - tqdm==4.65.0
      - traitlets==5.12.0
      - transformers==4.30.2
      - triton==2.0.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.0.4
      - wandb==0.15.11
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - wheel==0.38.4
      - widgetsnbextension==4.0.9
